// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC99jA6FF0rZ3bMSdKX7-ZqyfH6Yx403vw',
    appId: '1:80017196203:web:d39a6b1e791ac34557e3ee',
    messagingSenderId: '80017196203',
    projectId: 'hydrosheild-ec4b0',
    authDomain: 'hydrosheild-ec4b0.firebaseapp.com',
    storageBucket: 'hydrosheild-ec4b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1oo-W7KGUtzDo8QZeZgvk2FW1_0YiuU4',
    appId: '1:80017196203:android:237b5e2848a207fe57e3ee',
    messagingSenderId: '80017196203',
    projectId: 'hydrosheild-ec4b0',
    storageBucket: 'hydrosheild-ec4b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWQ6XBfhqkTZi1LUH1866bURuH9nynAxM',
    appId: '1:80017196203:ios:6210baefb7d0205257e3ee',
    messagingSenderId: '80017196203',
    projectId: 'hydrosheild-ec4b0',
    storageBucket: 'hydrosheild-ec4b0.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWQ6XBfhqkTZi1LUH1866bURuH9nynAxM',
    appId: '1:80017196203:ios:6210baefb7d0205257e3ee',
    messagingSenderId: '80017196203',
    projectId: 'hydrosheild-ec4b0',
    storageBucket: 'hydrosheild-ec4b0.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC99jA6FF0rZ3bMSdKX7-ZqyfH6Yx403vw',
    appId: '1:80017196203:web:0a2430dd8b1b2edb57e3ee',
    messagingSenderId: '80017196203',
    projectId: 'hydrosheild-ec4b0',
    authDomain: 'hydrosheild-ec4b0.firebaseapp.com',
    storageBucket: 'hydrosheild-ec4b0.firebasestorage.app',
  );

}