// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC99jA6FF0rZ3bMSdKX7-ZqyfH6Yx403vw',
    appId: '1:80017196203:web:d39a6b1e791ac34557e3ee',
    messagingSenderId: '80017196203',
    projectId: 'hydrosheild-ec4b0',
    authDomain: 'hydrosheild-ec4b0.firebaseapp.com',
    storageBucket: 'hydrosheild-ec4b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIt4JZc-CihVltP3gZtcP59h4LlIciA6o',
    appId: '1:413054055520:android:91babad9af1050dab0ff05',
    messagingSenderId: '413054055520',
    projectId: 'hydroshield1-f336f',
    storageBucket: 'hydroshield1-f336f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwaSLa79HIBtwOg6P1APkJqg-2vgvMBjA',
    appId: '1:413054055520:ios:1251e726d641759db0ff05',
    messagingSenderId: '413054055520',
    projectId: 'hydroshield1-f336f',
    storageBucket: 'hydroshield1-f336f.firebasestorage.app',
    iosClientId: '413054055520-hico0oovv5dn4bdca4uhtvv55g9up5bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.newGg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwaSLa79HIBtwOg6P1APkJqg-2vgvMBjA',
    appId: '1:413054055520:ios:1251e726d641759db0ff05',
    messagingSenderId: '413054055520',
    projectId: 'hydroshield1-f336f',
    storageBucket: 'hydroshield1-f336f.firebasestorage.app',
    iosClientId: '413054055520-hico0oovv5dn4bdca4uhtvv55g9up5bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.newGg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKesg7uYSyr6Z8AjwVsjsBoh700Dd9K6M',
    appId: '1:413054055520:web:9726ee0a4ce9b987b0ff05',
    messagingSenderId: '413054055520',
    projectId: 'hydroshield1-f336f',
    authDomain: 'hydroshield1-f336f.firebaseapp.com',
    storageBucket: 'hydroshield1-f336f.firebasestorage.app',
  );

}